language: go
go:
  - 1.2.2
  - 1.3.1
env:
  - GOARCH=amd64
  - GOARCH=386
script:
  - curl -s https://raw.githubusercontent.com/pote/gpm/v1.2.3/bin/gpm > gpm
  - chmod +x gpm
  - ./gpm install
  - ./test.sh
notifications:
  email: false
